//
//  IconlyIcon.swift
//  Dex
//
//  Created by Prateek Prakash on 10/6/26.
//

import SwiftUI

/// Every icon in the app: Iconly Pro, Light style, drawn from path data in
/// `IconlyGlyphs.swift` (generated by `Tools/iconly-paths.py`).
enum Iconly: String, CaseIterable {
    case menu, incognito, chevronDown, microphone, send, download, refresh, close, settings, add, folder, chat
    case edit, delete, more, pin, pinBold, check
    /// The round reference every glyph's optical size is matched to.
    case info
}

/// A glyph normalized to fill its 24-unit box, drawn centered in the rect at
/// `fill` of the rect's size.
struct IconlyShape: Shape {
    let icon: Iconly
    var fill: CGFloat = 1

    func path(in rect: CGRect) -> Path {
        let side = min(rect.width, rect.height) * fill
        let scale = side / 24
        return IconlyPath.parse(icon.path).applying(
            CGAffineTransform(translationX: rect.midX - side / 2, y: rect.midY - side / 2)
                .scaledBy(x: scale, y: scale)
        )
    }
}

/// An Iconly icon in a frame sized by its `Context`. The glyph's visible
/// extent is the frame × `fill`, so every icon reads the same size. Line
/// weight follows size (see `lineWidth`).
struct IconlyIcon: View {
    let icon: Iconly
    private let size: CGFloat

    /// Visible share of the frame: 20 of every 24 points, Sphinx's default.
    static let fill: CGFloat = 20.0 / 24

    init(_ icon: Iconly, _ context: Context) {
        self.icon = icon
        self.size = context.points
    }

    var body: some View {
        glyph
            .frame(width: size, height: size)
            // A stroked shape only hit-tests on its lines; take taps across the
            // whole frame.
            .contentShape(Rectangle())
    }

    @ViewBuilder
    private var glyph: some View {
        if Iconly.filled.contains(icon) {
            IconlyShape(icon: icon, fill: Self.fill)
                .fill(style: FillStyle(eoFill: true))
        } else {
            IconlyShape(icon: icon, fill: Self.fill)
                .stroke(style: StrokeStyle(
                    lineWidth: Self.lineWidth(size: size, fill: Self.fill),
                    lineCap: .round,
                    lineJoin: .round
                ))
        }
    }
    
    /// Points of stroke for an icon in a `size`-point frame. Below 24pt the
    /// weight follows the square root of the size, so small icons stay legible
    /// without tiny ones drawing heavy. Above 24pt (`.hero`) it grows in
    /// proportion.
    nonisolated static func lineWidth(size: CGFloat, fill: CGFloat) -> CGFloat {
        let scale = size < 24 ? (size / 24).squareRoot() : size / 24
        return Iconly.line * scale * fill
    }
}

extension IconlyIcon {
    /// Where an icon sits decides its size. Every glyph is matched at its base;
    /// call sites name a context, never a raw number. `.custom` is the escape
    /// hatch and needs a `// icon-size: <reason>` comment on the line above.
    enum Context: Equatable {
        case action       // 24: toolbar, drawer settings
        case tile         // 24: drawer rows (Folders, chats)
        case field        // 20: composer microphone
        case chip         // 20: an open chat's folder chip, beside its name
        case menu         // 20: menu item icons (drawn as images)
        case row          // 16: composer send arrow, pill button plus, folder tiles
        case inlineButton // 14: retry / dismiss on a failed pull
        case disclosure   // 12: model picker chevron
        case custom(CGFloat)

        var points: CGFloat {
            switch self {
            case .action: 24
            case .tile: 24
            case .field: 20
            case .chip: 20
            case .menu: 20
            case .row: 16
            case .inlineButton: 14
            case .disclosure: 12
            case .custom(let points): points
            }
        }
    }
}

extension Iconly {
    /// The glyph as an image, drawn exactly as `IconlyIcon` draws it, for
    /// places that take only an `Image`: menu items. A template, tinted like
    /// text, unless `tint` is given: menus don't tint a destructive item's
    /// image red on their own, so Delete passes `.systemRed`. A tint is
    /// drawn into the pixels, not attached with `withTintColor`: the
    /// toolbar draws a Menu label's image without applying that.
    @MainActor
    func image(_ context: IconlyIcon.Context, tint: UIColor? = nil) -> Image {
        let size = context.points
        let fill = IconlyIcon.fill
        let rect = CGRect(x: 0, y: 0, width: size, height: size)
        let rendered = UIGraphicsImageRenderer(size: rect.size).image { renderer in
            let cg = renderer.cgContext
            cg.addPath(IconlyShape(icon: self, fill: fill).path(in: rect).cgPath)
            let ink = (tint ?? .textPrimary).cgColor
            cg.setFillColor(ink)
            cg.setStrokeColor(ink)
            if Iconly.filled.contains(self) {
                cg.fillPath(using: .evenOdd)
            } else {
                cg.setLineWidth(IconlyIcon.lineWidth(size: size, fill: fill))
                cg.setLineCap(.round)
                cg.setLineJoin(.round)
                cg.strokePath()
            }
        }
        guard tint != nil else { return Image(uiImage: rendered.withRenderingMode(.alwaysTemplate)) }
        return Image(uiImage: rendered.withRenderingMode(.alwaysOriginal))
    }
}

/// Parses the absolute M/L/C/Z subset `Tools/iconly-paths.py` emits.
enum IconlyPath {
    static func parse(_ d: String) -> Path {
        var path = Path()
        var command: Character = " "
        var numbers: [CGFloat] = []

        func flush() {
            switch command {
            case "M" where numbers.count == 2:
                path.move(to: CGPoint(x: numbers[0], y: numbers[1]))
            case "L" where numbers.count == 2:
                path.addLine(to: CGPoint(x: numbers[0], y: numbers[1]))
            case "C" where numbers.count == 6:
                path.addCurve(to: CGPoint(x: numbers[4], y: numbers[5]),
                              control1: CGPoint(x: numbers[0], y: numbers[1]),
                              control2: CGPoint(x: numbers[2], y: numbers[3]))
            case "Z":
                path.closeSubpath()
            default:
                break
            }
            numbers.removeAll()
        }

        for token in d.split(separator: " ") {
            if let first = token.first, first.isLetter {
                flush()
                command = first
                if let value = Double(token.dropFirst()) { numbers.append(value) }
            } else if let value = Double(token) {
                numbers.append(value)
            }
        }
        flush()
        return path
    }
}
