#!/usr/bin/env python3
"""Generate `Dex/Models/EmojiShortcodeTable.swift` from GitHub's gemoji list.

Usage:
    curl -sSfL https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json -o /tmp/gemoji.json
    python3 Tools/emoji-shortcodes.py /tmp/gemoji.json

The table is one string of "name<TAB>emoji" lines, parsed once at first
use: a 1,900-entry dictionary literal type-checks slowly. gemoji is MIT
licensed; its notice is copied into the generated file.
"""
import json
import sys
from pathlib import Path

LICENSE = """Copyright (c) 2019 GitHub, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""


def main(source: str) -> None:
    entries = json.loads(Path(source).read_text())
    lines = []
    for entry in entries:
        for alias in entry["aliases"]:
            assert "\t" not in alias and "\n" not in alias and '"""' not in entry["emoji"]
            lines.append(f"{alias}\t{entry['emoji']}")
    lines.sort()
    license_comment = "\n".join("// " + line if line else "//" for line in LICENSE.splitlines())
    body = "\n".join(lines)
    out = f'''//
//  EmojiShortcodeTable.swift
//  Dex
//
//  Generated by Tools/emoji-shortcodes.py from GitHub's gemoji
//  (github.com/github/gemoji, db/emoji.json). Do not edit by hand.
//
//  gemoji's license:
//
{license_comment}
//

import Foundation

extension EmojiShortcodes {{
    /// "name<TAB>emoji", one alias per line ({len(lines)} aliases).
    static let source = """
{body}
"""
}}
'''
    Path("Dex/Models/EmojiShortcodeTable.swift").write_text(out)
    print(f"wrote {len(lines)} aliases")


if __name__ == "__main__":
    main(sys.argv[1])
